name: Continous Integration React Testing
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Install
        run: npm run build
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been built"
      - run: echo "Running Unit Test for repository ${{ github.repository }}"
      - name: Unit Test
        run: npm run test
      - run: echo "Running E2E Test for repository ${{ github.repository }}"
      - name: E2E Test
        run: npm run test:e2e:ci
      - name: Upload screenshots when specs fail
        if: ${{ failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./cypress/screenshots
      - name: Upload videos when specs fail
        if: ${{ failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: ./cypress/videos

